variable "composites_dir" {
  description = "Path to the directory containing the generated composite Lambda packages"
  type        = string
}

variable "asl_file" {
  description = "Path to the rendered Step Functions ASL workflow JSON file"
  type        = string
}

variable "dyno_requirements_file" {
  description = "Path to the dyno layer requirements.txt"
  type        = string
}

variable "dyno_layer_source_dir" {
  description = "Path to the root directory used to build the dyno Lambda layer zip"
  type        = string
}

# ── Random suffixes ───────────────────────────────────────────────────────────

# Generates a random suffix to ensure S3 bucket names are globally unique.
resource "random_string" "bucket_suffix" {
  length  = 6
  special = false
  upper   = false
}

# ── S3 cache bucket ───────────────────────────────────────────────────────────

# Provision an S3 bucket acting as a centralized data cache/store.
# This bucket is utilized by the composite Lambdas to pass large payloads or
# maintain state across the Step Functions workflow.
resource "aws_s3_bucket" "lambda_data_bucket" {
  bucket        = "learner-lab-composite-data-${random_string.bucket_suffix.result}"
  force_destroy = true
}

# ── Composite Lambda discovery ────────────────────────────────────────────────

# Dynamically scans the generated composites directory.
# This allows Terraform to provision a new Lambda function for *every* composite
# that our Python generation script created, without hardcoding their names.
locals {
  all_files = fileset(var.composites_dir, "**")
  lambda_dirs = toset([
    for file in local.all_files : split("/", file)[0]
    if length(split("/", file)) > 1
  ])
}

# ── Dyno Lambda layer ─────────────────────────────────────────────────────────

# A local execution block that bundles the shared code and pip dependencies
# into a structured format that AWS Lambda requires for a Layer (/python/...).
resource "null_resource" "build_dyno_layer" {
  triggers = {
    requirements_hash = filemd5(var.dyno_requirements_file)
    source_code_hash = sha1(join("", [
      for f in fileset("${var.dyno_layer_source_dir}", "**") :
      filesha1("${var.dyno_layer_source_dir}/${f}")
    ]))
  }

  provisioner "local-exec" {
    command = <<EOT
        set -e
        rm -rf ${path.module}/layer_staging
        mkdir -p ${path.module}/layer_staging/python/dyno
        cp -a ${var.dyno_layer_source_dir}/. ${path.module}/layer_staging/python/dyno/
        pip install -r ${var.dyno_requirements_file} -t ${path.module}/layer_staging/python/
      EOT
  }
}

# Zips the staging directory into an artifact ready for AWS upload.
data "archive_file" "dyno_layer_zip" {
  depends_on  = [null_resource.build_dyno_layer]
  type        = "zip"
  source_dir  = "${path.module}/layer_staging"
  output_path = "${path.module}/build_zips/dyno_layer.zip"
}

# Registers the Lambda layer in AWS, providing shared utilities across all composite Lambdas.
resource "aws_lambda_layer_version" "dyno_layer" {
  filename         = data.archive_file.dyno_layer_zip.output_path
  layer_name       = "dyno_core_layer"
  source_code_hash = data.archive_file.dyno_layer_zip.output_base64sha256
}

# ── Lambda functions ──────────────────────────────────────────────────────────

# Generates individual zip artifacts for every discovered composite directory.
data "archive_file" "lambda_zips" {
  for_each    = local.lambda_dirs
  type        = "zip"
  source_dir  = "${var.composites_dir}/${each.value}"
  output_path = "${path.module}/build_zips/${each.value}.zip"
}

# Assumes an IAM role "LabRole" has been pre-provisioned (common in AWS Academy/Learner Labs).
data "aws_iam_role" "lab_role" {
  name = "LabRole"
}

# Iterates over all composite directories and deploys them as distinct Lambda functions.
# Each Lambda utilizes the same layer (dyno) and points to the dynamically
# generated 'main.py' orchestrator as its handler.
resource "aws_lambda_function" "dynamic_lambdas" {
  for_each = local.lambda_dirs

  function_name    = each.value
  filename         = data.archive_file.lambda_zips[each.value].output_path
  source_code_hash = data.archive_file.lambda_zips[each.value].output_base64sha256
  layers           = [aws_lambda_layer_version.dyno_layer.arn]
  role             = data.aws_iam_role.lab_role.arn
  runtime          = "python3.14"
  handler          = "main.lambda_handler"
  memory_size      = 512

  environment {
    variables = {
      BUCKET_NAME = aws_s3_bucket.lambda_data_bucket.id
    }
  }
}

# ── Step Functions state machine ──────────────────────────────────────────────

# Provisions the macro-orchestrator using the ASL JSON generated by our second python script.
# This state machine sequences the executions of the dynamic Lambdas created above.
resource "aws_sfn_state_machine" "workflow" {
  name       = "CompositeWorkflow"
  role_arn   = data.aws_iam_role.lab_role.arn
  definition = file(var.asl_file)

  # Ensures Lambdas are fully provisioned before the state machine attempts to reference them.
  depends_on = [aws_lambda_function.dynamic_lambdas]
}

# ── Outputs ───────────────────────────────────────────────────────────────────

output "data_bucket_name" {
  value = aws_s3_bucket.lambda_data_bucket.id
}

output "deployed_functions" {
  value = [for f in aws_lambda_function.dynamic_lambdas : f.function_name]
}

output "state_machine_arn" {
  value = aws_sfn_state_machine.workflow.arn
}
